# This file is part of the YesWiki Extension stats.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  stats_activated: false
  # for edit config action
  stats_editable_config_params:
    - stats_activated
services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Stats\Service\:
    resource: 'services/*'